### ISSUE TITLE
Fenix tagged searches default metric for Jetstream uses deprecated definition, migrate to newer version

### ISSUE THREAD

**Issue by danielkberry** [mozilla/metric-hub#34]
The definition [here](https://github.com/mozilla/metric-hub/blob/main/definitions/fenix.toml#L166) is marked as deprecated but used as default [here](https://github.com/mozilla/metric-hub/blob/main/jetstream/defaults/fenix.toml#L8)

**Comment by ahmd-sh** [comment]
Hey, can I try this? It'll be my first time contributing to an open source proj. :)
