### ISSUE TITLE
Exclude 'toast_notification' and 'toolbar_badge' as part of other_ping_volume

### ISSUE THREAD

**Issue by nuggetsnegin** [mozilla/metric-hub#469]
The onboarding, messaging and communications team would like to exclude two ping types ([toolbar_badge](https://searchfox.org/mozilla-central/source/browser/components/asrouter/content-src/templates/OnboardingMessage/ToolbarBadgeMessage.schema.json) and [toast_notification](https://searchfox.org/mozilla-central/source/browser/components/asrouter/content-src/templates/ToastNotification/ToastNotification.schema.json)) as part of the [other_ping_volume](https://github.com/mozilla/metric-hub/blob/main/opmon/firefox-messaging-system.toml#L169) so we could more accurately monitor [undesired pings in looker](https://mozilla.cloud.looker.com/explore/firefox_desktop/messaging_system?toggle=fil&qid=8QSWQ2kZKK95uR8ULKGqpn). 

We'd like to have new lines added in the graph for both of these pings.

**Comment by dmose** [comment]
> The onboarding, messaging and communications team would like to include two ping types

@nuggetsnegin I got confused by how this was written. How about re-wording to `exclude two more known ping types`?
