### ISSUE TITLE
Y-Axis labels of charts in Browser Active Users say "Daily Active Users" for MAU and WAU.

### ISSUE THREAD

**Issue by edugfilho** [mozilla/metric-hub#512]
Link: https://mozilla.cloud.looker.com/dashboards/1178

<img width="2670" alt="Screenshot 2024-07-10 at 11 49 22 AM" src="https://github.com/mozilla/metric-hub/assets/5804462/e1510293-98db-46d6-8629-9753f76c50b8">

**Comment by bochocki** [comment]
Great catch, thank you! This is fixed.
